name: TestPlugin
version: 1.0
author: Diaboy01
main: me.marvin.Main
api-version: 1.12
load: POSTWORLD
depend: [LuckPerms]

commands:
  add:
  invite:
  create:
  role:
  farmwelt:
  wtp:
  modifydamage:
  teambase:
  accept: